import assert from 'node:assert/strict';
import fs from 'node:fs';
const origin='http://localhost:5510';
const path=new URL('../.env.auth-test',import.meta.url);
const data=JSON.parse(fs.readFileSync(path,'utf8'));
const post=(route,payload,cookie='',source=origin)=>fetch(origin+'/api/auth/'+route,{method:'POST',headers:{'Content-Type':'application/json',Origin:source,Cookie:cookie},body:JSON.stringify(payload)});
assert.equal((await post('setup',{...data,token:'0'.repeat(64)})).status,403);
const activation=await post('setup',data);
assert([200,409].includes(activation.status),'setup: '+await activation.text());
assert.equal((await post('setup',data)).status,409,'one-time setup');
assert.equal((await post('login',data,'','https://untrusted.example')).status,403,'login CSRF');
assert.equal((await post('login',{...data,password:'incorrect'})).status,401);
assert.equal((await post('login',{email:'unknown@example.com',password:'incorrect'})).status,401);
const login=await post('login',data);assert.equal(login.status,200,'login');
let setCookie=login.headers.get('set-cookie');assert.match(setCookie,/HttpOnly/i);assert.match(setCookie,/SameSite=Strict/i);
let cookie=setCookie.split(';')[0];
assert.equal((await fetch(origin+'/api/content?admin=1',{headers:{Cookie:cookie}})).status,200);
assert.equal((await fetch(origin+'/api/content?admin=1',{headers:{'oai-authenticated-user-id':'local_seedy','oai-authenticated-user-email':'ohridski@gmail.com'}})).status,403,'ChatGPT headers grant no access');
assert.equal((await post('password',{currentPassword:'incorrect',password:'a-strong-new-password'},cookie)).status,401);
const changed=await post('password',{currentPassword:data.password,password:data.password+'N'},cookie);assert.equal(changed.status,200,'password change');
const oldPassword=data.password;data.password+='N';fs.writeFileSync(path,JSON.stringify(data),{mode:0o600});
assert.equal((await fetch(origin+'/api/content?admin=1',{headers:{Cookie:cookie}})).status,403,'old session revoked');
assert.equal((await post('login',{...data,password:oldPassword})).status,401,'old password rejected');
const newLogin=await post('login',data);assert.equal(newLogin.status,200);cookie=newLogin.headers.get('set-cookie').split(';')[0];
assert.equal((await post('logout',{},cookie)).status,200);
assert.equal((await fetch(origin+'/api/content?admin=1',{headers:{Cookie:cookie}})).status,403,'logout revokes session');
let limited=false;for(let i=0;i<11;i++){const r=await post('setup',{...data,token:'0'.repeat(64)});if(r.status===429){limited=true;break;}}
assert(limited,'setup rate limiting');
console.log('PASS: one-time activation, email/password login, CSRF, password change, session revocation, logout, rate limiting, no ChatGPT access.');
