import { allEntries, db, isAdmin, sameOrigin } from '@/lib/server';
import { initialEntries } from '@/lib/content';
import { z } from 'zod';
const safeUrl=z.string().max(2000).refine(v=>!v||v.startsWith('/api/files/')||['/school.jpg','/stem.jpg','/application-2021-2022.docx','/schedule-2025-2026.pdf'].includes(v)||/^https:\/\//.test(v),'Използвайте защитен https адрес.');
// Gallery and attachments are stored as JSON text; empty string means none.
const jsonList=(inner:z.ZodTypeAny)=>z.string().max(60000).default('').refine(v=>{if(!v)return true;try{return inner.safeParse(JSON.parse(v)).success;}catch{return false;}},'Невалиден списък');
const schema=z.object({id:z.string().regex(/^[a-zA-Z0-9-]{1,100}$/),kind:z.enum(['news','document','team','admission','page','schedule','menu']),title:z.string().trim().min(2).max(200),body:z.string().max(30000),category:z.string().max(150),year:z.string().regex(/^\d{4}\/\d{4}$/),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),image:safeUrl,file:safeUrl,source:safeUrl,details:z.string().max(30000),gallery:jsonList(z.array(safeUrl.refine(Boolean)).max(300)),attachments:jsonList(z.array(z.object({name:z.string().trim().min(1).max(200),url:safeUrl.refine(Boolean)})).max(50)),published:z.union([z.literal(0),z.literal(1)])}).superRefine((entry,ctx)=>{if(['menu','schedule'].includes(entry.kind)&&entry.details){try{const rows=JSON.parse(entry.details);if(!Array.isArray(rows)||rows.length>100||!rows.every(r=>Array.isArray(r)&&r.length===(entry.kind==='schedule'?6:3)&&r.every(c=>typeof c==='string'&&c.length<=1000)))throw new Error();}catch{ctx.addIssue({code:z.ZodIssueCode.custom,message:'Невалидна таблица',path:['details']});}}if(entry.kind==='admission'&&entry.details){try{const data=JSON.parse(entry.details);if(!data||typeof data!=='object'||Array.isArray(data)||!Object.values(data).every(v=>typeof v==='string'))throw new Error();}catch{ctx.addIssue({code:z.ZodIssueCode.custom,message:'Невалиден прием',path:['details']});}}});
export async function GET(req:Request){try{const admin=new URL(req.url).searchParams.has('admin');if(admin&&!await isAdmin())return Response.json({error:'Необходим е администраторски достъп.'},{status:403});return Response.json({entries:await allEntries(admin)},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Информацията временно не е достъпна.'},{status:503});}}
export async function POST(req:Request){if(!sameOrigin(req)||!await isAdmin())return Response.json({error:'Нямате права за редакция.'},{status:403});try{if(Number(req.headers.get('content-length')||0)>200000)return Response.json({error:'Твърде голяма публикация.'},{status:413});const result=schema.safeParse(await req.json());if(!result.success)return Response.json({error:'Проверете заглавието, годината, датата и адресите.'},{status:400});const e=result.data;await db().prepare('INSERT INTO entries (id,kind,title,body,category,year,date,image,file,source,details,gallery,attachments,published) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,title=excluded.title,body=excluded.body,category=excluded.category,year=excluded.year,date=excluded.date,image=excluded.image,file=excluded.file,source=excluded.source,details=excluded.details,gallery=excluded.gallery,attachments=excluded.attachments,published=excluded.published').bind(e.id,e.kind,e.title,e.body,e.category,e.year,e.date,e.image,e.file,e.source,e.details,e.gallery,e.attachments,e.published).run();return Response.json({ok:true});}catch{return Response.json({error:'Публикацията не е записана. Опитайте отново.'},{status:503});}}

// Built-in entries live in lib/content.ts, so deleting one stores a 'deleted' tombstone that hides it.
export async function DELETE(req:Request){if(!sameOrigin(req)||!await isAdmin())return Response.json({error:'Нямате права за изтриване.'},{status:403});const id=new URL(req.url).searchParams.get('id')||'';if(!/^[a-zA-Z0-9-]{1,100}$/.test(id))return Response.json({error:'Невалиден запис.'},{status:400});try{if(initialEntries.some(e=>e.id===id))await db().prepare("INSERT INTO entries (id,kind,title,published) VALUES (?,'deleted','',0) ON CONFLICT(id) DO UPDATE SET kind='deleted',published=0").bind(id).run();else await db().prepare('DELETE FROM entries WHERE id=?').bind(id).run();return Response.json({ok:true});}catch{return Response.json({error:'Записът не е изтрит. Опитайте отново.'},{status:503});}}
