'use client';
import { useEffect, useState } from 'react';
import { usePathname } from 'next/navigation';
import { Phone, Mail, MapPin, ArrowUpRight, Search, ChevronDown, Menu, X, BookOpen } from 'lucide-react';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from '@/components/ui/dropdown-menu';
import { Sheet, SheetTrigger, SheetClose, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { navigation, useful, documentSections, documentSectionHref } from '@/lib/content';
import { sectionIcons } from '@/app/section-icons';
const sectionAt=(href:string)=>documentSections.find(s=>documentSectionHref(s)===href);
const isIn=(path:string,href:string)=>path===href||path.startsWith(href+'/');
export function SiteHeader(){const path=usePathname();const [open,setOpen]=useState(false);return <><a className="skip-link" href="#main">Към основното съдържание</a><header className="site-header"><div className="topbar"><div className="wrap"><span><a href="tel:035063641"><Phone size={13}/>0350 6 36 41</a><a href="mailto:info-1302630@edu.mon.bg"><Mail size={14}/>info-1302630@edu.mon.bg</a></span><a href="https://app.shkolo.bg/" target="_blank" rel="noreferrer">Електронен дневник <ArrowUpRight size={13}/></a></div></div><div className="wrap nav-row"><a href="/" className="brand"><img src="/logo.jpg" alt="Лого на училището" width="57" height="59"/><span>СУ „Св. Климент Охридски“<small>град Пещера · Основано през 1907 г.</small></span></a><nav aria-label="Главно меню">{navigation.map(n=>n.items?<DropdownMenu key={n.title}><DropdownMenuTrigger className={'nav-trigger'+(n.items.some(([,href])=>isIn(path,href))?' active':'')}>{n.title}<ChevronDown size={12}/></DropdownMenuTrigger><DropdownMenuContent align="start" className="nav-menu">{n.items.map(([title,href])=>{const s=sectionAt(href);const Icon=s&&sectionIcons[s.slug];return <DropdownMenuItem asChild key={href}><a href={href}>{Icon&&<span className="nav-menu-icon"><Icon className="size-[18px] text-inherit"/></span>}<span className="nav-menu-text"><strong>{title}</strong>{s?.note&&<small>{s.note}</small>}</span></a></DropdownMenuItem>;})}<DropdownMenuItem asChild><a className="nav-menu-all" href="/documents">Всички документи<ArrowUpRight className="size-4 text-inherit"/></a></DropdownMenuItem></DropdownMenuContent></DropdownMenu>:<a key={n.title} href={n.href} className={path===n.href?'active':''} aria-current={path===n.href?'page':undefined}>{n.title}</a>)}</nav><a className="search-icon" href="/search" aria-label="Търсене"><Search size={20}/></a><div className="mobile-menu"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger aria-label="Отвори меню"><Menu/></SheetTrigger><SheetContent className="mobile-sheet" showCloseButton={false}><SheetClose className="sheet-close" aria-label="Затвори меню"><X size={20}/></SheetClose><SheetHeader><SheetTitle>Меню</SheetTitle><SheetDescription>СУ „Св. Климент Охридски“</SheetDescription></SheetHeader><nav aria-label="Мобилно меню">{navigation.map(n=>n.items?<details key={n.title}><summary>{n.title}</summary>{n.items.map(([title,href])=><a key={href} href={href} onClick={()=>setOpen(false)}>{title}</a>)}</details>:<a key={n.title} href={n.href} onClick={()=>setOpen(false)}>{n.title}</a>)}</nav></SheetContent></Sheet></div></div></header></>}
export function SiteFooter(){return <><section className="useful-section wrap"><div><BookOpen size={24}/><h2>Полезни връзки</h2></div><div>{useful.map(([t,h])=><a key={h} href={h} target="_blank" rel="noreferrer">{t}<ArrowUpRight size={17}/></a>)}</div></section><footer><div className="wrap footer-grid"><div><a className="brand" href="/"><img src="/logo.jpg" alt="Лого на училището" loading="lazy"/><span>СУ „Св. Климент Охридски“<small>град Пещера</small></span></a><p>Повече от век знание, традиция и вдъхновение. Заедно създаваме възможности за утрешния ден.</p></div><div><h3>За училището</h3><a href="/school/mission">Мисия</a><a href="/school/history">История</a><a href="/team">Екип</a><a href="/council/public">Обществен съвет</a><a href="/budget">Бюджет</a><a href="/documents">Документи</a><a href="/documents/archive">Архив на документите</a></div><div><h3>За учениците</h3><a href="/admissions">Прием</a><a href="/schedule">Седмично разписание</a><a href="/scholarships">Стипендии</a><a href="/council/students">Ученически съвет</a></div><div><h3>За родителите</h3><a href="https://app.shkolo.bg/">Електронен дневник</a><a href="/menu">Ученическо меню</a><a href="/parents">Полезна информация</a><a href="/services">Заявления и декларации</a></div><div><h3>Контакти</h3><a href="tel:035063641"><Phone size={13}/>0350 6 36 41</a><a href="mailto:info-1302630@edu.mon.bg"><Mail size={13}/>info-1302630@edu.mon.bg</a><a href="/contacts"><MapPin size={14}/>ул. „Димчо Дебелянов“ №4,<br/>гр. Пещера</a></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} СУ „Св. Климент Охридски“. Всички права запазени.</span><span><a href="/privacy">Поверителност</a></span></div></footer></>}
export function CookieNotice(){const [visible,setVisible]=useState(false);useEffect(()=>{setVisible(!localStorage.getItem('school-privacy-choice'));},[]);function accept(){localStorage.setItem('school-privacy-choice','necessary');setVisible(false);}return visible?<aside className="cookie-notice" aria-label="Информация за бисквитките"><div><strong>Вашата поверителност е важна.</strong><p>Използваме само необходимите технологии. Външната карта се зарежда след Ваш избор. <a href="/privacy">Научете повече</a></p></div><button className="btn green" onClick={accept}>Разбрах</button></aside>:null;}
