export type Entry = {id:string;kind:string;title:string;body:string;category:string;year:string;date:string;image:string;file:string;source:string;details:string;published:number};
export const currentYear = (date = new Date()) => {const y=date.getMonth()>=8?date.getFullYear():date.getFullYear()-1;return `${y}/${y+1}`;};
export const mission='Създаваме възможно най-добрите условия за развитие на личността и потенциала на всеки ученик, така че той да постигне пълноценна трудова и социална интеграция. Предоставяме качествено образование, което формира креативни, социално отговорни и пълноценно интегрирани личности. Следваме принципите на истината, доброто, непрекъснатото лично усъвършенстване и успешната лична реализация.';
export const history=[['1907','Поставено е началото на Пещерската непълна смесена гимназия.'],['1922','Ново начало с 63 ученици.'],['1937','Свети Климент Охридски е избран за патрон.'],['1939','Училището става пълна смесена гимназия.'],['1940','Завършва първият випуск.'],['1957','Училището е наградено с орден „Кирил и Методий“, II степен.'],['1969','Създаден е първият в България електромеханичен клас-автомат КОМ-ПАК-69.'],['1979','Завършена е новата училищна сграда.'],['1982','Училището получава орден „Кирил и Методий“, I степен.'],['1984–1986','Навлизат компютрите и е оборудвана компютърна зала.'],['1995','Създаден е танцов ансамбъл „Славейче“.'],['2005 и 2010','Сградата е обновена и санирана.'],['2019','Обновено е техническото оборудване.'],['Днес','Развиваме STEM образование и обучение в направление „Софтуерни и хардуерни науки“.']];
export const documentCategories=['Учебни планове','Правилници','Планове','Програми','Графици','Мерки','Етичен кодекс','Заповеди','Други документи','Заявления','Декларации','Бюджет','Стипендии','Ученически съвет','Обществен съвет'];
export const pages:Record<string,{title:string;description:string}>={
 '/':{title:'Начало',description:'Традиция, която гледа напред. Училището на знанието и възможностите в Пещера.'},
 '/school/mission':{title:'Нашата мисия',description:'Образование за утрешния ден. Възможности за развитие на всеки ученик.'},
 '/school/history':{title:'Повече от век история',description:'От първите класни стаи през 1907 г. до съвременната STEM среда.'},
 '/team':{title:'Нашият екип',description:'Хората, които превръщат знанието във вдъхновение.'},
 '/admissions':{title:'Прием на ученици',description:'Открийте следващата стъпка в образованието на Вашето дете.'},
 '/admissions/1':{title:'Прием в I клас',description:'Първите големи открития започват тук.'},
 '/admissions/5':{title:'Прием в V клас',description:'Нови знания и нови хоризонти.'},
 '/admissions/8':{title:'Прием в VIII клас',description:'Избери своята посока.'},
 '/admissions/11':{title:'Прием в XI клас',description:'Поглед към бъдещето.'},
 '/news':{title:'Новини и обявления',description:'Събития, постижения и важни моменти от живота на училището.'},
 '/documents':{title:'Документи',description:'Училищните документи на едно място, подредени по категория и учебна година.'},
 '/documents/archive':{title:'Архив на документите',description:'Документацията и заповедите от началото на предишните учебни години – подредени по години и раздели, готови за изтегляне.'},
 '/schedule':{title:'Седмично разписание',description:'Изберете клас и учебна година, за да видите публикуваното разписание.'},
 '/menu':{title:'Ученическо меню',description:'Седмично меню, дати и информация за алергените.'},
 '/scholarships':{title:'Стипендии',description:'Условия, срокове и необходими документи.'},
 '/parents':{title:'За родителите',description:'Полезна информация за всеки учебен ден.'},
 '/council/students':{title:'Ученически съвет',description:'Състав, дейности, решения и документи.'},
 '/council/public':{title:'Обществен съвет',description:'Заедно за развитието на училището.'},
 '/budget':{title:'Бюджет',description:'Прозрачност и отчетност. Финансови документи по години.'},
 '/services':{title:'Административни услуги',description:'Заявления и декларации за изтегляне.'},
 '/contacts':{title:'Свържете се с нас',description:'Тук сме, за да отговорим на Вашите въпроси.'},
 '/search':{title:'Търсене в сайта',description:'Намерете страници, новини, документи и информация за прием.'},
 '/privacy':{title:'Поверителност и бисквитки',description:'Как обработваме информацията, която споделяте с нас.'},
};
export const navigation=[{title:'Начало',href:'/'},{title:'Училище',items:[['Мисия','/school/mission'],['История','/school/history'],['Екип','/team'],['Ученически съвет','/council/students'],['Обществен съвет','/council/public'],['Бюджет','/budget']]},{title:'Прием',items:[['Първи клас','/admissions/1'],['Пети клас','/admissions/5'],['Осми клас','/admissions/8'],['Единадесети клас','/admissions/11']]},{title:'Ученици',items:[['Стипендии','/scholarships'],['Седмично разписание','/schedule']]},{title:'Родители',items:[['Електронен дневник','https://app.shkolo.bg/'],['Ученическо меню','/menu'],['Полезна информация','/parents']]},{title:'Новини',href:'/news'},{title:'Услуги',items:[['Заявления','/services?category=Заявления'],['Декларации','/services?category=Декларации']]},{title:'Документи',items:[...documentCategories.slice(0,9).map(c=>[c,'/documents?category='+encodeURIComponent(c)]),['Архив по години','/documents/archive']]},{title:'Контакти',href:'/contacts'}];
export const useful=[['Министерство на образованието и науката','https://www.mon.bg/'],['Държавна агенция за закрила на детето','https://www.sacp.government.bg/'],['Национален образователен портал','https://start.e-edu.bg/'],['Електронен дневник Shkolo','https://app.shkolo.bg/']];
const base={kind:'news',category:'STEM',year:'2025/2026',file:'',details:'',published:1};
export const initialEntries:Entry[]=[{...base,id:'stem-opening',title:'Новият STEM център: бъдещето започва днес',date:'2026-06-09',body:'В училището е открит нов STEM център с кабинети по природни науки, предприемачество и информационни технологии. Учениците представят експерименти, дигитални проекти и предприемачески идеи. Новата среда създава възможности за практическо обучение, научни изследвания и работа в екип.',image:'/stem.jpg',source:'https://ohridski.eu/2026/06/09/%d0%be%d1%82%d0%ba%d1%80%d0%b8%d0%b2%d0%b0%d0%bd%d0%b5-%d0%bd%d0%b0-stem-%d1%86%d0%b5%d0%bd%d1%82%d1%8a%d1%80-2/'},{...base,id:'stem-invitation',title:'Покана за откриване на STEM центъра',date:'2026-05-27',body:'Публикувана е официална покана за откриването на училищния STEM център. Материалът е от учебната 2025/2026 година и се съхранява в архива.',image:'/school.jpg',source:'https://ohridski.eu/2026/05/27/%d0%be%d1%82%d0%ba%d1%80%d0%b8%d0%b2%d0%b0%d0%bd%d0%b5-%d0%bd%d0%b0-stem-%d1%86%d0%b5%d0%bd%d1%82%d1%8a%d1%80/'},{...base,id:'offers-2025',category:'Обявления',title:'Покана за представяне на оферти',date:'2025-09-02',body:'Архивна покана за представяне на оферти. Оригиналният документ е достъпен в официалната публикация на училището.',image:'/school.jpg',source:'https://ohridski.eu/2025/09/02/%d0%bf%d0%be%d0%ba%d0%b0%d0%bd%d0%b0-%d0%b7%d0%b0-%d0%bf%d1%80%d0%b5%d0%b4%d1%81%d1%82%d0%b0%d0%b2%d1%8f%d0%bd%d0%b5-%d0%bd%d0%b0-%d0%be%d1%84%d0%b5%d1%80%d1%82%d0%b8/'}];
export const fileSize=(bytes:number)=>bytes>=1e6?(bytes/1e6).toLocaleString('bg-BG',{maximumFractionDigits:1})+' MB':Math.max(1,Math.round(bytes/1e3))+' KB';
export const fileType=(url:string)=>(url.split('?')[0].split('.').pop()||'').toUpperCase();
// Name for a downloaded file: the document title without characters that file systems reject.
export const downloadName=(title:string,url:string)=>title.replace(/[\\/:*?"<>|]+/g,'-').replace(/[.\s]+$/,'')+'.'+fileType(url).toLowerCase();
export function entryHref(e:Entry){return e.kind==='news'?'/news/'+e.id:e.kind==='admission'?'/admissions/'+e.category:e.kind==='team'?'/team':e.kind==='page'?e.category:'/documents?q='+encodeURIComponent(e.title)+'&year='+encodeURIComponent(e.year);}
initialEntries.push({id:'schedule-archive-2025',kind:'document',title:'Седмично разписание — табло на класовете',body:'Официален архивен документ, публикуван през февруари 2026 г. Не използвайте като актуално разписание.',category:'Графици',year:'2025/2026',date:'',file:'/schedule-2025-2026.pdf',image:'',source:'https://ohridski.eu/седмично-разписание/',details:'',published:1},{id:'application-archive-2021',kind:'document',title:'Заявление-декларация за записване в I клас',body:'Архивен образец за учебната 2021/2022 година. Предназначен е за справка, а не за текущия прием.',category:'Заявления',year:'2021/2022',date:'',file:'/application-2021-2022.docx',image:'',source:'https://ohridski.eu/заявления/',details:'',published:1});
export type TeamMember={name:string;role:string;email:string;group:TeamGroup;photo?:string};
export type TeamGroup='Ръководство'|'Педагогически екип'|'Администрация'|'Помощен персонал';
export const teamGroups:TeamGroup[]=['Ръководство','Педагогически екип','Администрация','Помощен персонал'];
// Staff photos: put the file in public/team/ and add a line here, keyed by the part of the email before @.
// Example: 'radka.ibisheva':'/team/radka.ibisheva.jpg'. People without a photo show their initials.
export const teamPhotos:Record<string,string>={};
const t=(group:TeamGroup,rows:[string,string,string][])=>rows.map(([name,role,email])=>({name,role,email:email+'@edu.mon.bg',group,photo:teamPhotos[email]}));
export const team:TeamMember[]=[
 ...t('Ръководство',[['Павлинка Антониева Шопова-Начкова','Директор','pavlinka.shopova-nachkova'],['Радка Лазарова Попова','Заместник-директор','radka.ibisheva']]),
 ...t('Педагогически екип',[['Айрие Нуреттин Пехливан','Начален учител','ayrie.pehlivan'],['Айлин Емин Павлова','Учител по английски език','ailin.pavlova'],['Анастасия Викторова Мераклиева','Учител по физика и математика','anastasia.meraklieva'],['Аксиния Петкова Попова','Начален учител','aksinia.popova'],['Събка Божидарова Ковачева','Учител по български език','sabka.kovacheva'],['Георги Иванов Шопов','Учител по физическо възпитание и спорт','georgi.iv.shopov1'],['Гергана Веселинова Ангелчова','Учител по история и география','gergana.angelchova'],['Дамяна Иванова Райкова-Янева','Учител ГЦОУД','damiana.raikova'],['Димка Николова Герджикова','Учител по математика','dimka.gerdzhikova'],['Евгения Ангелова Дамянова','Учител ГЦОУД','evgenia.a.damianova'],['Елена Тодорова Гивечева-Михова','Педагогически съветник','elena.t.givecheva'],['Елена Николова Доркова','Учител ГЦОУД','elena.dorkova'],['Илиана Росенова Пейковска','Учител по химия','iliana.peykovska'],['Кристина Руменова Хаджиева','Учител ГЦОУД','kristina.hadzhieva'],['Христина Огнянова Илинчева','Учител ГЦОУД','hristina.ilincheva'],['Мария Иванова Стоименова','Учител по музика','maria.iv.stoimenova'],['Мария Михайлова Атанасова','Учител по информационни технологии','maria.mi.atanasova'],['Милена Георгиева Балтаджиева','Учител по изобразително изкуство','milena.baltadzhieva'],['Милен Николаев Бараков','Учител ГЦОУД','milen.ni.barakov'],['Нина Стоева Гемджиян','Начален учител','nina.gemdzhiian'],['Нели Илиева Славова','Учител по български език','neli.il.slavova'],['Ивелина Георгиева Димитрова','Начален учител ГЦОУД','ivelina.ge.dimitrova1'],['Петя Иванова Георгиева','Учител по биология','petya.iv.georgieva1'],['Екатерина Христова','Учител по английски език','ekaterina.iv.hristova'],['Николай Георгиев Щерев','Учител по физическо възпитание и спорт','nikolai.shcherev'],['Христина Костадинова Хаджиева','Учител по история и география','hristina.hadzhieva'],['Цветка Павлова Петкова','Учител по български език','tsvetka.petkova'],['Юсуф Ахмедов Мехмедов','Учител по информационни технологии','yusuf.mehmedov']]),
 ...t('Администрация',[['Цветана Стоянова Кънчева','Счетоводител','tsvetana.kancheva'],['Мария Петрова Цветанова','Завеждащ административна служба','mariia.pe.tsvetanova'],['Сузана Илианова Денисова','Домакин','suzana.denisova']]),
 ...t('Помощен персонал',[['Нели Димитрова Благоева','Хигиенист','neli.di.blagoeva'],['Даниела Димитрова Босева','Хигиенист','daniela.boseva'],['Нина Атанасова Атанасова','Хигиенист','nina.at.atanasova'],['Райна Петрова Гюзелева','Хигиенист','rayna.gyuzeleva'],['Сезгин Юсеинова Веиз','Хигиенист','sezgin.veiz'],['Димитър Йорданов Мантаров','Огняр','dimitar.io.mantarov'],['Ясен Левентов Билянов','Работник поддръжка','iasen.bilianov']]),
];
