import { Fragment } from 'react';
import { notFound } from 'next/navigation';
import ScrollAnimations from '../ScrollAnimations';
import { ArrowUpRight, Download, Users, BookOpen } from 'lucide-react';
import { pages, mission, useful, currentYear } from '@/lib/content';
import { safeEntries } from '@/lib/server';
import { Admissions, Contact, Documents, NewsList, SchoolMenu, SchoolSchedule, SiteSearch, TeamDirectory, HistoryStory } from '../content-ui';
import { ArchiveBanner, ArchiveOverview } from '../archive';
import { DocumentSections } from '../documents';
import { ArchiveBrowser } from '../archive-ui';
import { archiveFiles, archiveYears } from '@/lib/archive';
const archiveYear=(path:string)=>archiveYears.find(y=>path==='/documents/archive/'+y.slug);
const archivePage=(path:string)=>{const y=archiveYear(path);return y?{title:'Архив '+y.year,description:'Документация и заповеди от началото на учебната '+y.year+' година – по раздели и папки, с изтегляне на отделни документи и цели папки.'}:undefined;};
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const path='/'+slug.join('/');const {entries}=await safeEntries();const article=path.startsWith('/news/')?entries.find(e=>e.id===slug[1]&&e.kind==='news'):null;const meta=archivePage(path)||pages[path];const title=article?.title||meta?.title||'Страницата не е намерена';const description=article?.body.slice(0,155)||meta?.description||'Информация за СУ „Св. Климент Охридски“, Пещера.';const image=article?article.image: '/school.jpg';return {title:title+' | СУ „Св. Климент Охридски“',description,openGraph:{title,description,images:image?[image.startsWith('https:')?image:'https://kliment-peshtera-school.balakchiev09.chatgpt.site'+image]:[],locale:'bg_BG',type:article?'article':'website'}};}
export default async function Page({params,searchParams}:{params:Promise<{slug:string[]}>;searchParams:Promise<Record<string,string|undefined>>}){const {slug}=await params;const query=await searchParams;const path='/'+slug.join('/');const {entries,unavailable}=await safeEntries();const article=path.startsWith('/news/')?entries.find(e=>e.id===slug[1]&&e.kind==='news'):null;const year=archiveYear(path);const page=article?{title:article.title,description:article.category+' · '+article.date}:archivePage(path)||pages[path];if(!page)notFound();const parents=slug.slice(0,-1).map((_,i)=>'/'+slug.slice(0,i+1).join('/')).filter(p=>pages[p]);const records=entries.filter(e=>e.kind==='page'&&e.category===path);return <main id="main"><section className="page-heading"><div className="wrap"><div className="breadcrumb"><a href="/">Начало</a>{parents.map(p=><Fragment key={p}><span>/</span><a href={p}>{pages[p].title}</a></Fragment>)}<span>/</span><span>{page.title}</span></div><h1>{page.title}</h1><p>{page.description}</p></div></section><div className="wrap page-content">{unavailable&&<p className="notice">Част от информацията временно не е достъпна. Показваме потвърдените основни материали.</p>}
{path==='/school/mission'&&<div className="mission-page"><img src="/stem.jpg" alt="Технологии в училищния STEM център"/><div><h2>Образование за утрешния ден</h2><p className="lead">{mission}</p><div className="values"><span><BookOpen/>Качествено образование</span><span><Users/>Личностно развитие</span></div><a className="btn green" href="/team">Запознайте се с нашия екип <ArrowUpRight size={17}/></a></div></div>}
{path==='/school/history'&&<><ScrollAnimations/><HistoryStory/></>}
{path==='/news'&&<NewsList entries={entries.filter(e=>e.kind==='news')}/>}
{article&&<article className="article-page">{article.year!==currentYear()&&<p className="notice">Архивна публикация · учебна година {article.year}</p>}{article.image&&<img src={article.image} alt={article.title}/>}<p className="preserve-lines lead">{article.body}</p>{article.file&&<a className="btn outline" href={article.file} download><Download size={18}/>Приложен документ</a>}{article.source&&<p className="source"><a href={article.source} target="_blank" rel="noreferrer">Източник: официалният сайт на училището <ArrowUpRight size={15}/></a></p>}<a className="text-link" href="/news">Всички новини</a></article>}
{['/documents','/services','/budget','/scholarships','/council/students','/council/public'].includes(path)&&<>{records.map(e=><article className="text-section" key={e.id}><h2>{e.title}</h2><p className="preserve-lines">{e.body}</p></article>)}{['/scholarships','/council/students','/council/public'].includes(path)&&!records.length&&<p className="notice">Съставът, условията и актуалните решения предстои да бъдат предоставени от училището. Не са добавени непотвърдени имена или срокове.</p>}{path==='/documents'&&!query.category&&!query.q&&!query.year?<DocumentSections entries={entries}/>:<>{path==='/documents'&&<ArchiveBanner/>}<Documents entries={entries.filter(e=>e.kind==='document')} initialCategory={query.category||({'/budget':'Бюджет','/scholarships':'Стипендии','/council/students':'Ученически съвет','/council/public':'Обществен съвет','/services':'Заявления'}[path]||'Всички категории')} initialQuery={query.q||''} initialYear={query.year}/></>}</>}
{path==='/team'&&<TeamDirectory extra={entries.filter(e=>e.kind==='team'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e.details))}/>}
{path==='/admissions'&&<div className="admission-grid">{[['1','I','Първите големи открития'],['5','V','Нови знания, нови хоризонти'],['8','VIII','Избери своята посока'],['11','XI','Поглед към бъдещето']].map(([n,r,t])=><a key={n} href={'/admissions/'+n}><span className="class-number">{r}<small>клас</small></span><h3>{t}</h3><span>График и документи <ArrowUpRight size={17}/></span></a>)}</div>}
{path.startsWith('/admissions/')&&<Admissions grade={slug[1]} entries={entries.filter(e=>e.kind==='admission')}/>}
{path==='/schedule'&&<SchoolSchedule entries={entries.filter(e=>e.kind==='schedule')}/>}
{path==='/menu'&&<SchoolMenu entries={entries.filter(e=>e.kind==='menu')}/>}
{path==='/documents/archive'&&<ArchiveOverview entries={entries}/>}
{year&&<ArchiveBrowser year={year} years={archiveYears} files={archiveFiles(year.year,entries)}/>}
{path==='/parents'&&<><div className="information-grid">{[['Електронен дневник','Оценки, отсъствия и комуникация с училището.','https://app.shkolo.bg/'],['Ученическо меню','Хранене, седмично меню и алергени.','/menu'],['Седмично разписание','Учебната седмица на Вашето дете.','/schedule'],['Заявления и декларации','Образци на административни документи.','/services']].map(([t,d,h])=><a key={h} href={h}><h2>{t}</h2><p>{d}</p><ArrowUpRight size={21}/></a>)}</div>{records.map(e=><article className="text-section" key={e.id}><h2>{e.title}</h2><p className="preserve-lines">{e.body}</p></article>)}</>}
{path==='/contacts'&&<Contact/>}{path==='/search'&&<SiteSearch entries={entries} initialQuery={query.q||''}/>}
{path==='/privacy'&&<article className="article-page privacy"><h2>За тази версия на сайта</h2><p>Този сайт е нова версия за преглед на училищната информация. Публикуваните новини съдържат връзки към официалния си източник. Преди обществено използване училището следва да потвърди съдържанието и тази информация за поверителност.</p><h2>Контактна форма</h2><p>При изпращане съхраняваме име, фамилия, имейл, предоставен телефон и съобщение в защитената входяща кутия. Те са достъпни само за определения администратор и се използват за обработка на запитването. Не се изпраща автоматично имейл. За защита от спам се съхраняват еднократен формулярен идентификатор и хеш на IP адреса.</p><h2>Бисквитки и външно съдържание</h2><p>Сайтът не използва рекламни или аналитични бисквитки. Изборът Ви за информационния банер се запазва в браузъра. Администрацията използва необходима сесийна бисквитка за вход с имейл и парола. Паролите се съхраняват като защитени хешове. Google Maps се зарежда само след натискане на „Покажи Google карта“, когато Google получава данни за връзката Ви. Връзките към Shkolo и другите външни сайтове имат собствени политики.</p><h2>Въпроси и искания</h2><p>За въпроси относно информацията, която сте предоставили, пишете на <a href="mailto:info-1302630@edu.mon.bg">info-1302630@edu.mon.bg</a> или се обадете на 0350 6 36 41. Не изпращайте здравни данни, ЕГН или други чувствителни данни чрез формата.</p><p>Сроковете за съхранение и окончателните правила за обработка на лични данни трябва да бъдат определени от училището преди публичното въвеждане в експлоатация.</p></article>}
</div></main>}
